# Loading packages
library(dplyr)



# Loading the tables
original_gene_counts <- read.csv(file = '~/Downloads/Lab-6-Omics/TCGA_BRCA_Gene_ReadCounts.txt', sep = '\t', header = TRUE)
clinical_annotation <- read.csv(file = '~/Downloads/Lab-6-Omics/TCGA_BRCA_ClinicalAnnotation.txt', sep = '\t', header = TRUE)

ref_gene_table <- read.csv(file = '~/Downloads/Lab-6-Omics/mart_export.txt', sep = '\t', header = TRUE)
abundance_counts_table <- read.csv(file = '~/Downloads/Lab-6-Omics/output/abundance.tsv', sep = '\t', header = TRUE)


# Adds the genes that match a transcript to the table generated by Kallisto
abundance_counts_table$Gene=ref_gene_table$Gene_name[match(abundance_counts_table$target_id, ref_gene_table$RefSeq_match_transcript)]

# omit transcripts that don't have a matching gene
abundance_counts_table <- na.omit(abundance_counts_table)

# create table with counts for each gene
gene_counts <- abundance_counts_table %>% group_by(Gene) %>% summarise(counts = sum(est_counts))

# add original patient counts to the gene_counts table
gene_counts$original_counts=original_gene_counts$TCGA.C8.A138.01[match(gene_counts$Gene, original_gene_counts$Gene)]

# omit genes that don't have a matching gene in original patient counts
gene_counts <- na.omit(gene_counts)

# create table with only the counts
plot_table <- select(gene_counts, original_counts, counts)

# remove rows with 0 counts
plot_table_without_0 <- filter(plot_table, original_counts > 0, counts > 0)

# plot the counts from the table against our estimated counts
plot(plot_table_without_0, xlim=c(1e-2,1e+8), ylim=c(1e-2,1e+8), log='xy', pch=20, xlab="TCGA-C8-A138-01 Patient Counts", ylab="Estimated Counts", main="Comparison between our estimates and table counts")

# plot the counts from the table against our estimated counts with the trendline
fit <- lm(log(counts) ~ log(original_counts), data=plot_table_without_0)
coeff=coefficients(fit)
eq = paste0("Equation: y = ", round(coeff[2],1), "*x ", round(coeff[1],1))
mtext(eq, side=3)
abline(fit, col="blue")

